version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./production/app/Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - public-data:/var/www/top_ten/public
  redis:
    image: redis
    command: redis-server
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./production/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - public-data:/var/www/top_ten/public

volumes:
  postgres-data:
  public-data:
